const stats=[['10K+','Happy Users'],['₹25L+','Value Processed'],['100%','Secure Tracking'],['24/7','Support']];
const steps=[['01','Create Account','Register with your mobile number and Gmail.'],['02','See What We Need','Only active admin requirements appear to you.'],['03','Submit Your Card','Enter valid card details and send for review.'],['04','Get Paid to UPI','After approval, payment goes directly to your UPI.']];
const benefits=['No wallet balance required','Admin-controlled requirements','Direct UPI / QR payouts','Clear order status & history','Fraud warning before submission','Electricity bill opportunities'];
export default function Home(){return <main>
<div className="tricolor"><span/><span/><span/></div>
<header><a className="logo" href="#home"><b>Card</b><strong>Sell</strong><small>SELL GIFT CARDS • EARN INSTANTLY</small></a><nav><a href="#home">Home</a><a href="#how">How It Works</a><a href="#requirements">Requirements</a><a href="#benefits">Benefits</a></nav><div className="actions"><a className="login" href="/login">Login</a><a className="primary" href="/register">Create Account</a></div></header>
<section id="home" className="hero"><div className="heroText">
<div className="indiaPill"><span>🇮🇳</span><div><b>PROUDLY MADE IN INDIA</b><small>Indian-first platform • UPI ready</small></div></div>
<div className="eyebrow">A SIMPLE WAY TO SELL GIFT CARDS</div><h1>Your gift card.<br/><em>Your cash.</em></h1>
<p className="lead">Sell only the gift cards CardSell currently needs. Get clear status updates and receive approved payouts directly to your UPI.</p>
<div className="heroBtns"><a className="primary big" href="/register">Start Selling <span>→</span></a><a className="secondary big" href="#requirements">View Requirements</a></div>
<div className="trustRow"><span>✓ Direct UPI payout</span><span>✓ No wallet required</span><span>✓ Secure review</span></div></div>
<div className="visual"><div className="glow g1"/><div className="glow g2"/><div className="indiaSeal"><span>🇮🇳</span><b>INDIA</b><small>BUILT HERE</small></div>
<div className="giftCard"><div className="gcTop"><span>CARDSell</span><small>GIFT CARD</small></div><div className="gcValue">₹1,000</div><div className="gcBottom"><span>READY TO SELL</span><i>•••• 2481</i></div></div>
<div className="upiCard"><div className="upiMark">↗</div><div><b>UPI PAYOUT</b><small>Direct to your UPI ID</small></div><strong>₹960</strong></div>
<div className="reviewCard"><span>✓</span><div><b>Verified Review</b><small>Admin checks every sale</small></div></div></div></section>
<section className="indiaStrip"><div><span>🇮🇳</span><div><b>Made in India</b><small>Designed for Indian users</small></div></div><div><span>UPI</span><div><b>Direct payout</b><small>No wallet balance</small></div></div><div><span>↗</span><div><b>Transparent</b><small>Track every transaction</small></div></div></section>
<section className="stats">{stats.map(s=><div key={s[1]}><b>{s[0]}</b><span>{s[1]}</span></div>)}</section>
<section id="how" className="section"><div className="sectionHead"><span>HOW CARDSELL WORKS</span><h2>Simple from start to payout.</h2><p>No confusing steps. See what is required, submit, track and get paid.</p></div><div className="steps">{steps.map(x=><div className="step" key={x[0]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p><span className="stepArrow">↗</span></div>)}</div></section>
<section id="requirements" className="darkSection"><div className="sectionHead"><span>LIVE REQUIREMENTS</span><h2>We buy what we need.</h2><p>Admin controls which gift cards are currently required. Users see only active requirements.</p></div><div className="reqCard"><div className="reqMain"><div className="reqLabel"><span className="liveDot"/> ACTIVE REQUIREMENT</div><div className="brandLine"><div className="brandIcon">A</div><div><h3>Amazon Gift Card</h3><p>Current example requirement</p></div></div><div className="reqMeta"><span>Required: <b>₹10,000</b></span><span>Example rate: <b>96%</b></span><span>Min discount: <b>3%</b></span></div></div><div className="progress"><div className="progressHead"><div><small>RECEIVED</small><b>₹0</b></div><div><small>REMAINING</small><b>₹10,000</b></div></div><div className="bar"><span/></div><small>Remaining amount updates automatically after approved sales.</small></div></div></section>
<section id="benefits" className="section benefits"><div className="benefitIntro"><span>WHY CARDSELL</span><h2>Built around trust.</h2><p>Clear requirements, secure review and direct payouts—without a wallet sitting between you and your money.</p><a className="outline" href="/register">Create your account →</a></div><div className="benefitGrid">{benefits.map(x=><div key={x}><span>✓</span><b>{x}</b></div>)}</div></section>
<section className="indiaClosing"><div className="closingBadge">🇮🇳</div><div className="closingText"><small>MADE IN INDIA</small><h2>Built for India. Built around UPI.</h2><p>One clean platform for gift-card selling and electricity bill opportunities.</p></div><a className="primary" href="/register">Join CardSell</a></section>
<footer><div className="logo"><b>Card</b><strong>Sell</strong><small>SELL GIFT CARDS • EARN INSTANTLY</small></div><p>© 2026 CardSell. Made in India.</p><div><a href="/login">Login</a> · <a href="/register">Create Account</a> · Privacy · Terms · Support</div><a href="/admin/login" style={{marginLeft:16}}>Admin</a></footer></main>}
